version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000 # si no se hizo Heroku
    command: gunicorn config.wsgi -b 0.0.0.0:8000 # si se hizo Heroku
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=RgkW8YhLLoUiWHycxu2Hv0ivHJ-x3-KOL-lDUFRNjcK-va-5cEw"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: